version: 0.2
phases:
  build:
    commands:
      - sudo apt install hugo -y
      - echo Starting build
      - hugo --config hugo.toml
      - echo Build finished
artifacts:
  name: "BuildOutput"
  files:
    - "**/*"
  base-directory: public
    